### ISSUE TITLE
Icon for README.md 

### ISSUE THREAD

**Issue by sgse** [torvic9/bash-scripts#8]
For the eyes ;)
of course only if you like :) if not, delete.

![t9-bench-sgs](https://user-images.githubusercontent.com/17575778/53911655-5c840880-4057-11e9-90d5-e58704a8b6a7.png)
![t9-bench02--sgs](https://user-images.githubusercontent.com/17575778/53911659-60178f80-4057-11e9-994d-506a745f172e.png)
![t9-bench03--sgs](https://user-images.githubusercontent.com/17575778/53911668-64dc4380-4057-11e9-8692-35c887be83c7.png)

Something better has not occurred to me so far ;)
cu

like
\<img src="https://github.com/torvic9/bash-scripts/blob/master/icon.png"/>

**Comment by torvic9** [comment]
Thanks :)
